### ISSUE TITLE
Support option for diff/2 that tells it to return maps instead of structs

### ISSUE THREAD

**Issue by AHBruns** [corka149/jsonpatch#19]
I want to persist my patch operations generated by diff/2 to apply them later. I know that apply_patches/2 can take map representations of operations, but diff/2 can't generate them. The has lead me to extract that struct -> map conversion logic out into my code. It would have been preferable if I could have just have diff generate the operations in the format I wanted them.

**Comment by corka149** [comment]
Are you able to share how you want to persist the patches? I want to better understand what causes issues in those cases.

**Comment by AHBruns** [comment]
Sure. I have a system which tracks a very large piece of state in memory. When this state is changed, the system diffs the old and new states, then writes an event to and event stream noting what changed. The system is periodically restarted, and when it is restarted it replays the event stream to recreate the state it had when it was stopped.

I'm using this library to both for the state diffing (patch generation, and event replaying (patch application). The events are stored as serialized JSON blobs. So, I need the patches I generate to be simple maps which can my event store can serialize.

**Comment by corka149** [comment]
I decided to primary use maps as it makes a let of sense in regards to compatibility and usability with other libraries and Phoenix.

The new version 2.1.0 will be released today.
