### ISSUE TITLE
Applying list of multilple operations where the first op is Remove leads to an erroneous behaviour

### ISSUE THREAD

**Issue by gaynetdinov** [corka149/jsonpatch#6]
**Describe the bug**
Applying a list of ops where the first op is `Remove` would lead to the wrong result.

**To Reproduce**
```elixir

    test "Apply patch with multilple operations" do
      patch = [
        %Jsonpatch.Operation.Remove{path: "/age"},
        %Jsonpatch.Operation.Add{path: "/age", value: 34},
        %Jsonpatch.Operation.Replace{path: "/age", value: 35}
      ]

      target = %{"age" => "33"}
      patched = Jsonpatch.apply_patch!(patch, target)

      assert %{"age" => 35} = patched
    end
```

The test above should be green according to my understanding, however, it would fail and the `patched` would be an empty map.

**Expected behaviour**

The test above should be green.

**Additional context**
If I apply the ops from my example above one by one, it would behave correctly.

**Comment by corka149** [comment]
Hi @gaynetdinov

quoting from [RFC-6902](https://datatracker.ietf.org/doc/html/rfc6902#section-3)

> Operations are applied sequentially in the order they appear in the array.

The current bug is that it order the patch operations. This is wrong. I will remove the sorting and add your test.

Thanks for sharing this.

**Comment by gaynetdinov** [comment]
Thanks for the quick fix!
